src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Distributor</fullName>
        <active>true</active>
        <label>Distributor</label>
    </recordTypes>
    <recordTypes>
        <fullName>End_User</fullName>
        <active>true</active>
        <label>End User</label>
    </recordTypes>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Applications_of__c</fullName>
        <label>Applications of Interest</label>
        <picklist>
            <picklistValues>
                <fullName>BAS Connectivity (HVAC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Batch Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calibration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concrete Vibrators</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Acquisition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Calculator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flow Meter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fluid Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SCADA Connectivity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility Meter Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility Meter Reading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wireless Communications</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Lines of Interest</label>
        <picklist>
            <picklistValues>
                <fullName>Automotive Fluid Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BEACON AMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blancett</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concrete Fluid Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coriolis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Acquisition / Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dynasonics Ultrasonic Meters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Series Meters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flo-Tech</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flow Dynamics Calibration Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flow Dynamics Calibrator Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Galaxy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hedland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Impeller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial Oval Gear (IOG)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial Turbo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ModMAG M-Series</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitors / Accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ORION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preso DP Meters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Racine Vortex Meters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recordall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research Control Valves (RCV)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services/Technical Field Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vortex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wyco Tool</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Purchase_Timeframe__c</fullName>
        <description>Anticipated timeframe in which customer will purchase product</description>
        <inlineHelpText>Anticipated timeframe in which customer will purchase product</inlineHelpText>
        <label>Purchase Timeframe</label>
        <picklist>
            <picklistValues>
                <fullName>within 1 month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1-3 months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4-6 months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7+ months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&lt; 1 year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 years</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/SendLeadEmailController_Test.cls
/**
 	@author: Lennard Santos (CloudSherpas)
 	@description: Test Coverage for SendLeadEmailController
 	@Date Created: Nov 21 2013
 */
@isTest
private class SendLeadEmailController_Test {
	
	static Account createTestData_Account(){
        RecordType rt = [Select Id from RecordType WHERE sObjectType = 'Account' AND DeveloperName = :'End_User']; 
        Account testAccount = new Account(
        	Name = 'Test Account',
        	RecordTypeId = rt.Id
        );
        insert testAccount;
        return testAccount;
        
    }
	
	static Contact createTestData_Contact(Account acct,String email){
		Contact testContact = new Contact(
			LastName = 'Test Contact',
			AccountId = acct.Id,
			Email = email
		);
		insert testContact;
		return testContact;
	}
	
	static Lead createTestData_Lead(){
		Lead testLead = new Lead(
			LastName = 'TestLead',
			Title = 'CEO',
			Company = 'Green Systems',
			LeadSource = 'Distributor',
			Website = 'www.greensystem.com',
			Industry = 'Aerospace',
			Purchase_Timeframe__c = 'within 1 month',
			Phone = '12345678',
			Email = 'test@greensystem.com',
			Applications_Of__c = 'Calibration;Monitor',
			Product__c = 'Coriolis;Communications'
		);
		insert testLead;
		return testLead;
	}
	
	static Campaign createTestData_Campaign(){
		Campaign testCampaign = new Campaign(
			Name = 'ABC',
			IsActive = true
		);
		insert testCampaign;
		return testCampaign;
	}
	
	static CampaignMember createTestData_CampMember(Campaign camp,Lead leadRec){
		CampaignMember testCmpMember = new CampaignMember(
			CampaignId = camp.Id,
			LeadId = leadRec.Id,
			Status = 'Sent'
		);
		insert testCmpMember;
		return testCmpMember;
	}
	
    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        Test.startTest();
        	Account testAccount = createTestData_Account();
        	Contact testContact = createTestData_Contact(testAccount,'mary@barnyard.com');
        	Lead testLead = createTestData_Lead();
        	Campaign testCamp = createTestData_Campaign();
        	CampaignMember testCampMember = createTestData_CampMember(testCamp,testLead);
        	PageReference pageRef = Page.SendEmailPopup;
        Test.setCurrentPageReference(pageRef);
        	System.currentPageReference().getParameters().put('id',testLead.Id);	
        	ApexPages.Standardcontroller s = new ApexPages.Standardcontroller(testLead);
        	SendLeadEmailController sendLeadCon = new SendLeadEmailController(s);	
        	System.assertEquals(sendLeadCon.campName, testCamp.Name);
        	sendLeadCon.showEmailPopup();
        	sendLeadCon.searchString = 'Lead';
        	sendLeadCon.searchBtn();
        	System.assert(sendLeadCon.conList.isEmpty());
        	sendLeadCon.searchString = 'Contact';
        	sendLeadCon.searchBtn();
        	System.assert(!sendLeadCon.conList.isEmpty());
        	sendLeadCon.saveConList();
        	sendLeadCon.conList[0].isChecked = true;
        	sendLeadCon.saveConList();
        	sendLeadCon.closeEmailPopup();
        	sendLeadCon.showManualPopup();
        	sendLeadCon.hideManualPopup();
        	sendLeadCon.strEmail = 'test@salesforce.com';
        	sendLeadCon.addManualAddress();
        	System.debug('\n\nCONLIST SELECTED : '+sendLeadCon.conListSelected + '\n\n');
        	sendLeadCon.conListSelected[0].isChecked = true;
        	sendLeadCon.removeFromList();
        Test.setCurrentPageReference(sendLeadCon.sendMassEmail());
        	System.debug('\n\n\n'+System.currentPageReference()+'\n\n\n');
        	
        Test.stopTest();
    }
    
    static testMethod void testOtherScenario(){
    	Test.startTest();
    	System.debug('\n\n\n*******************TEST OTHER SCENARIO*********************\n\n\n');
    		Account testAccount = createTestData_Account();
        	Contact testContact = createTestData_Contact(testAccount,'mary@barnyard.com');
        	Lead testLead = createTestData_Lead();
        	Campaign testCamp = createTestData_Campaign();
        	CampaignMember testCampMember = createTestData_CampMember(testCamp,testLead);
        	PageReference pageRef = Page.SendEmailPopup;
        	Test.setCurrentPageReference(pageRef);
        	System.currentPageReference().getParameters().put('id',testLead.Id);	
        	ApexPages.Standardcontroller s = new ApexPages.Standardcontroller(testLead);
        	SendLeadEmailController sendLeadCon = new SendLeadEmailController(s);
        	sendLeadCon.sendMassEmail();
        	System.debug('\n\nCONLIST SELECTED : ' + sendLeadCon.conListSelected);
        	System.debug('\n\nEMAIL STRING : ' + sendLeadCon.strEmailsplitted);
    		System.debug('\n\n\n'+System.currentPageReference()+'\n\n\n');
    	Test.stopTest();
    	
    }
    
    static testMethod void testContactwithNoEmail(){
    	Test.startTest();
    	System.debug('\n\n\n*******************TEST CONTACT WITH NO EMAIL*********************\n\n\n');
    		Account testAccount = createTestData_Account();
        	Contact testContact = createTestData_Contact(testAccount,'');
        	Lead testLead = createTestData_Lead();
        	Campaign testCamp = createTestData_Campaign();
        	CampaignMember testCampMember = createTestData_CampMember(testCamp,testLead);
        	PageReference pageRef = Page.SendEmailPopup;
        	Test.setCurrentPageReference(pageRef);
        	System.currentPageReference().getParameters().put('id',testLead.Id);	
        	ApexPages.Standardcontroller s = new ApexPages.Standardcontroller(testLead);
        	SendLeadEmailController sendLeadCon = new SendLeadEmailController(s);
        	sendLeadCon.searchString = 'Contact';
        	sendLeadCon.searchBtn();
        	System.debug('\n\n\nCONTACT SEARCH LIST :  '+sendLeadCon.conList + '\n\n\n');
        	sendLeadCon.conList[0].isChecked = true;
        	sendLeadCon.saveConList();
        	sendLeadCon.sendMassEmail();
        	System.debug('\n\nCONLIST SELECTED : ' + sendLeadCon.conListSelected);
        	System.debug('\n\nEMAIL STRING : ' + sendLeadCon.strEmailsplitted);
    		System.debug('\n\n\n'+System.currentPageReference()+'\n\n\n');
    	Test.stopTest();
    	
    }
}