src/objects/Geo_Data_Map__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flow_Regional_Sales_Manager__c</fullName>
        <label>Flow Regional Sales Manager</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flow_Territory__c</fullName>
        <label>Flow Territory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ST__c</fullName>
        <label>ST</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UAccount_Manager__c</fullName>
        <label>UAccount Manager</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Uterritory_2__c</fullName>
        <label>Uterritory 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Uterritory_Name__c</fullName>
        <label>Uterritory Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip3__c</fullName>
        <label>Zip3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Geo Data Map</label>
    <nameField>
        <label>Geo Data Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geo Data Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Organization_Type__c</fullName>
        <label>Organization Type</label>
        <picklist>
            <picklistValues>
                <fullName>Utility Distributor (UD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility Customer (UC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instrumentation Representative (IR)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instrumentation Customer (IC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instrumentation Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Lines of Interest</label>
        <picklist>
            <picklistValues>
                <fullName>Automotive Fluid Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BEACON AMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blancett</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concrete Fluid Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coriolis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Acquisition / Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dynasonics Ultrasonic Meters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-Series Meters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flo-Tech</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flow Dynamics Calibration Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flow Dynamics Calibrator Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Galaxy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hedland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Impeller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial Oval Gear (IOG)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial Turbo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ModMAG M-Series</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitors / Accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ORION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preso DP Meters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Racine Vortex Meters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recordall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research Control Valves (RCV)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services/Technical Field Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vortex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wyco Tool</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Territory_Name_2__c</fullName>
        <label>Territory Name</label>
        <picklist>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Midwest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UTerritory_Name__c</fullName>
        <label>UTerritory Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Utility</fullName>
        <active>true</active>
        <businessProcess>Utility Leads</businessProcess>
        <description>This is the template that will align with the Utility lead process(es).</description>
        <label>Utility</label>
    </recordTypes>
</CustomObject>

src/classes/LeadTriggerManagerTest.cls
@isTest
public class LeadTriggerManagerTest {

    static Lead l1;
    
    public static void leadTestData (Id recordTypeId, String postalCode) {
        // create at least 5 data
        l1 = new Lead();
        l1.RecordTypeId = recordTypeId;
        l1.FirstName = 'John';
        l1.LastName = 'Doe';
        l1.Company = 'Acme';
        l1.Organization_Type__c = 'Instrumentation Customer (IC)';
        l1.Status = 'Qualified';
        l1.Rating = 'Hot';
        l1.Product__c = 'Concrete Fluid Products';
        l1.Country = '';
        l1.State = '';
        l1.PostalCode = postalCode;
        
    }
    
    public static void geoDataMapTestData (){
        // Flow Record Type
        Geo_Data_Map__c g1 = new Geo_Data_Map__c();
        g1.Zip_Code__c = '56744';
        g1.City__c = 'Oslo';
        g1.County__c = 'Marshall';
        g1.State__c = 'Minnesota';
        g1.ST__c = 'MN';
        g1.Zip3__c = '567';
        g1.Flow_Territory__c = 'Midwest';
        g1.Flow_Regional_Sales_Manager__c = 'Tim Wissing';
        g1.Uterritory_2__c = 'MN1';
        g1.UAccount_Manager__c = 'Mike McNabb';
        g1.Uterritory_Name__c = 'Central';
        insert g1;
        
        Geo_Data_Map__c g2 = new Geo_Data_Map__c();
        g2.Zip_Code__c = '50001';
        g2.City__c = 'Ackworth';
        g2.County__c = 'Warren';
        g2.State__c = 'Iowa';
        g2.ST__c = 'IA';
        g2.Zip3__c = '500';
        g2.Flow_Territory__c = 'Central';
        g2.Flow_Regional_Sales_Manager__c = 'TBD';
        g2.Uterritory_2__c = 'IA1';
        g2.UAccount_Manager__c = 'Mike McNabb';
        g2.Uterritory_Name__c = 'Central';
        insert g2;
        
        Geo_Data_Map__c g3 = new Geo_Data_Map__c();
        g3.Zip_Code__c = '01002';
        g3.City__c = 'Amherst';
        g3.County__c = 'Hampshire';
        g3.State__c = 'Massachusetts';
        g3.ST__c = 'MA';
        g3.Zip3__c = '010';
        g3.Flow_Territory__c = 'Northeast';
        g3.Flow_Regional_Sales_Manager__c = 'Kevin Mahaffey';
        g3.Uterritory_2__c = 'MA1';
        g3.UAccount_Manager__c = 'Dan Johnson';
        g3.Uterritory_Name__c = 'East';
        insert g3;
        
        Geo_Data_Map__c g4 = new Geo_Data_Map__c();
        g4.Zip_Code__c = '27406';
        g4.City__c = 'Greensboro';
        g4.County__c = 'Guilford';
        g4.State__c = 'North Carolina';
        g4.ST__c = 'NC';
        g4.Zip3__c = '274';
        g4.Flow_Territory__c = 'Southeast';
        g4.Flow_Regional_Sales_Manager__c = 'Hixson Eldridge';
        g4.Uterritory_2__c = 'NC1';
        g4.UAccount_Manager__c = 'Craig Cardella';
        g4.Uterritory_Name__c = 'East';
        insert g4;
        
        // Utility Record Type
        Geo_Data_Map__c g5 = new Geo_Data_Map__c();
        g5.Zip_Code__c = '50430';
        g5.City__c = 'Corwith';
        g5.County__c = 'Hancock';
        g5.State__c = 'Iowa';
        g5.ST__c = 'IA';
        g5.Zip3__c = '504';
        g5.Flow_Territory__c = 'Central';
        g5.Flow_Regional_Sales_Manager__c = 'TBD';
        g5.Uterritory_2__c = 'IA1';
        g5.UAccount_Manager__c = 'Mike McNabb';
        g5.Uterritory_Name__c = 'Central';
        insert g5;
        
    }
    
    // add testmethod for before update too?
     public static testmethod void testTerritoryNameUpdateFlowRecord(){
         // add data to GDM Data Map
         geoDataMapTestData();
         
         Test.startTest();
         List<RecordType> recordTypes = [Select Name, Id from RecordType where SObjectType = 'Lead' AND Name like 'Flow%'];
         System.assertEquals(1, recordTypes.size());
         leadTestData(recordTypes.get(0).Id, '56744');
         
         Database.SaveResult resultL1 = Database.insert(l1);
         Test.stopTest();
         
         // asserts here
         System.assert(resultL1.isSuccess());
         
         List<Lead> leadList = [Select id, Territory_Name_2__c from Lead where id=:resultL1.getId()];
         System.assertEquals('Midwest', leadList.get(0).Territory_Name_2__c);
     }
     
    /*
     public static testmethod void testTerritoryNameUpdateUtilityRecord(){
         // testdata here
         leadTestData('Utility', '');
     }
	*/
     
}